# Basic
title: Michael
subtitle: Study Journal
description: Wlecome to my Study Journal
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Michael Zhu study life
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: stat / data
url: "https://mz-jhz.github.io"

# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    #disqus: leopard


    #disqus:
      #shortname: "leopard"
      #related_posts: false
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    mail: junhao.zhumichael@outlook.com


# ç™¾åº¦ç»Ÿè®¡
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#baidu:
    #id: 8ba1c6be0953b6f9c2ba38e57f615421

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#ga:
    #id: UA-84134159-3
    #host: auto


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    #title: Blog Home
    #url: "/archive"
    - {title: Blog Home, description: archive, url: '/archive'}

# Navigation buttons in the front page.s
nav:
    - {title: Articles, description: archive, url: '/archive'}
    - {title: Label, description: tags, url: '/tags'}
    - {title: tech support, description: support, url: '/support'}
    - {title: About me, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
